### ISSUE TITLE
Displaying Markers

### ISSUE THREAD

**Issue by eparadise** [code-for-chapel-hill/School-Meal-Mapper#1]
I cannot figure out how to modify the existing code in order to display all of the markers, instead of just displaying those that fit the need criteria (as we have gotten rid of this search box). I tried setting "markers = this.entries" in the filteredMarkers() method in App.vue and deleting the logic that filters this.entries. When I do this, I get the error "cannot read property 'contains' of null", and from my testing it seems as though this means that the bounds variable is null, although I cannot determine why that is the case. I'm currently using the same data that our original website uses, not the new spreadsheet. It would be great to get some advice from the developers who worked on the original site!

I have pushed what I currently have to branch "eliza-branch", with "markers = this.entries" commented out.

**Comment by a-rothwell** [comment]
I think this might be because App.vue contains a SearchFilter component that isn't rendered.

Removing the search filter in lines 17, 50, 97 fixed the null for me.

**Comment by eparadise** [comment]
Thank you! That was very helpful.
