### ISSUE TITLE
Displaying Business Details

### ISSUE THREAD

**Issue by eparadise** [code-for-chapel-hill/School-Meal-Mapper#2]
The site now works so that when it is loaded, all markers are visible and the results list appears on the left with all entries. However, I'm having some trouble with displaying the Business Details component. When a marker is clicked, the Business Details will not display immediately. Instead, one has to zoom out in order to get them to display. Any thoughts as to why this is happening? When an entry in the results list is clicked, the business details display right away.

**Comment by a-rothwell** [comment]
The function pass location is called on mouse click. In this function showList is set to false.
The function setBounds which is called on zoom, sets showList to true.

Fix: Line 194
`this.showList = true;`
