### ISSUE TITLE
Results displaying under business details

### ISSUE THREAD

**Issue by eparadise** [code-for-chapel-hill/School-Meal-Mapper#3]
Some results still show under the business details for resources that don't have long business details. I'm not sure why, as the results list should only display if showListing is true and business details should only display if showListing is false. Currently Business Details is being rendered inside ResultsList, which could be causing the issue. Any recommendations would be appreciated! I tried moving BusinessDetails out of ResultsList, but ran into some other issues.

NOTE: As a temporary fix, I have set the Business Details height to be 100vh, so that this doesn't happen. However, I'd really appreciate advice as to how to fix this, as this solution is a bit hack-y and doesn't look great (second screenshot)

<img width="285" alt="Screen Shot 2020-06-18 at 1 51 03 PM" src="https://user-images.githubusercontent.com/43389857/85054953-d2d44d80-b16a-11ea-941a-fd16da1670fb.png">
<img width="284" alt="Screen Shot 2020-06-18 at 2 01 01 PM" src="https://user-images.githubusercontent.com/43389857/85055815-2e530b00-b16c-11ea-9991-0fa7914d5afb.png">

**Comment by readingdancer** [comment]
It sounds like you need to check the code that sets the flag for showing business details is actually being set as it looks like it's not toggling the list on and off.
